CREATE TABLE [dbo].[Roles]
(
    [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    [Name] NVARCHAR(50) NOT NULL,
    [Description] NVARCHAR(500) NULL,
    [Permissions] NVARCHAR(MAX) NOT NULL,
    [IsSystemRole] BIT NOT NULL DEFAULT 0,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    [UpdatedAt] DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT [PK_Roles] PRIMARY KEY ([Id]),
    CONSTRAINT [UQ_Roles_Name] UNIQUE ([Name])
)
GO
